export const DEFAULT_THEME_LIGHTNESS = 0.7;
export const DEFAULT_THEME_LIGHTNESS_DARK_DELTA = -0.1;
export const DEFAULT_THEME_LIGHTNESS_LIGHT_DELTA = 0.1;

export const DEFAULT_SEMANTIC_DARK_L_VALUE = 0.45;
export const DEFAULT_SEMANTIC_LIGHT_L_VALUE = 0.55;
